"""added current field to DesignImage

Revision ID: 092b88f1c14c
Revises: 2c34173c1062
Create Date: 2019-07-02 17:40:35.337166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092b88f1c14c'
down_revision = '2c34173c1062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designimages', sa.Column('current', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'movies', ['title_EN'])
    op.create_unique_constraint(None, 'movies', ['title_DE'])
    op.drop_column('movies', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('title', sa.VARCHAR(length=32), nullable=True))
    op.drop_constraint(None, 'movies', type_='unique')
    op.drop_constraint(None, 'movies', type_='unique')
    op.drop_column('designimages', 'current')
    # ### end Alembic commands ###
