"""table names changed

Revision ID: 12345bb97bef
Revises: 25a84cbe208a
Create Date: 2019-06-13 10:23:48.104116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12345bb97bef'
down_revision = '25a84cbe208a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('awards', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('cinematography', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('color', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('directors', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('duration', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('editors', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('executive_producers', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('format', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('isColored', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('isReleased', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('language', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('producers', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('screenings', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('sound_mix', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('sound_recordist', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('supporters', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('synopsis', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('title_DE', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('title_EN', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'movies', ['title_EN'])
    op.create_unique_constraint(None, 'movies', ['title_DE'])
    op.drop_column('movies', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('title', sa.TEXT(length=32), nullable=True))
    op.drop_constraint(None, 'movies', type_='unique')
    op.drop_constraint(None, 'movies', type_='unique')
    op.drop_column('movies', 'title_EN')
    op.drop_column('movies', 'title_DE')
    op.drop_column('movies', 'synopsis')
    op.drop_column('movies', 'supporters')
    op.drop_column('movies', 'sound_recordist')
    op.drop_column('movies', 'sound_mix')
    op.drop_column('movies', 'screenings')
    op.drop_column('movies', 'producers')
    op.drop_column('movies', 'language')
    op.drop_column('movies', 'isReleased')
    op.drop_column('movies', 'isColored')
    op.drop_column('movies', 'format')
    op.drop_column('movies', 'executive_producers')
    op.drop_column('movies', 'editors')
    op.drop_column('movies', 'duration')
    op.drop_column('movies', 'directors')
    op.drop_column('movies', 'color')
    op.drop_column('movies', 'cinematography')
    op.drop_column('movies', 'awards')
    # ### end Alembic commands ###
