"""movie_contacts added

Revision ID: 1cc387c38a59
Revises: 245a4edd1485
Create Date: 2019-06-20 14:27:04.549339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc387c38a59'
down_revision = '245a4edd1485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('contact_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('movies_id', sa.INTEGER(), nullable=False),
    sa.Column('contact_id', sa.INTEGER(), nullable=False),
    sa.Column('contact_type', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['movies_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('movies_id', 'contact_id')
    )
    op.drop_table('movie_contacts')
    # ### end Alembic commands ###
