"""updated Link

Revision ID: 245a4edd1485
Revises: 7f0b48959cfb
Create Date: 2019-06-20 09:53:08.140314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245a4edd1485'
down_revision = '7f0b48959cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('contact_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'contact_type')
    # ### end Alembic commands ###
