"""added DesignImage table

Revision ID: 2c34173c1062
Revises: eec0f3c72613
Create Date: 2019-06-27 17:56:37.511160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c34173c1062'
down_revision = 'eec0f3c72613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('designimages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('link')
    op.create_unique_constraint(None, 'movies', ['title_DE'])
    op.create_unique_constraint(None, 'movies', ['title_EN'])
    op.drop_column('movies', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('title', sa.VARCHAR(length=32), nullable=True))
    op.drop_constraint(None, 'movies', type_='unique')
    op.drop_constraint(None, 'movies', type_='unique')
    op.create_table('link',
    sa.Column('movies_id', sa.INTEGER(), nullable=False),
    sa.Column('contact_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['movies_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('movies_id', 'contact_id')
    )
    op.drop_table('designimages')
    # ### end Alembic commands ###
