"""contact fields added

Revision ID: 5ff644b25bba
Revises: 36c5ac454ccd
Create Date: 2019-07-03 19:46:21.522647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff644b25bba'
down_revision = '36c5ac454ccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('contacts', sa.Column('profession', sa.String(length=120), nullable=True))
    op.add_column('contacts', sa.Column('surname', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'surname')
    op.drop_column('contacts', 'profession')
    op.drop_column('contacts', 'email')
    # ### end Alembic commands ###
