"""Added img_url

Revision ID: 9e7e48d66cae
Revises: 1cc387c38a59
Create Date: 2019-06-20 19:35:58.933891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e7e48d66cae'
down_revision = '1cc387c38a59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('img_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'img_url')
    # ### end Alembic commands ###
