"""added image_url column

Revision ID: eec0f3c72613
Revises: 7f0b48959cfb
Create Date: 2019-06-26 16:09:59.799742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec0f3c72613'
down_revision = '7f0b48959cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('image_url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'movies', ['title_DE'])
    op.create_unique_constraint(None, 'movies', ['title_EN'])
    op.drop_column('movies', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('title', sa.VARCHAR(length=32), nullable=True))
    op.drop_constraint(None, 'movies', type_='unique')
    op.drop_constraint(None, 'movies', type_='unique')
    op.drop_column('movies', 'image_url')
    # ### end Alembic commands ###
